Repository dftbplus/dftbplus, pull requests merged in 2020-04, with the labels that each got.

#433 Document change to clarify FermiLevel
  doc/dftb+/manual/transport.tex
Labels: Documentation

#442 Omp encharge none
  prog/dftb+/lib_dftb/encharges.F90
Labels: bug

#440 Partial fix for d4 crash
  prog/dftb+/lib_math/lapackroutines.F90
Labels: bug

#437 Temp profile fix
  CHANGELOG.rst
  doc/dftb+/manual/dftbp.tex
  prog/dftb+/lib_dftbplus/initprogram.F90
  prog/dftb+/lib_dftbplus/main.F90
  prog/dftb+/lib_dftbplus/parser.F90
  prog/dftb+/lib_md/andersentherm.F90
  prog/dftb+/lib_md/berendsentherm.F90
  prog/dftb+/lib_md/nhctherm.F90
  prog/dftb+/lib_md/tempprofile.F90
  test/prog/dftb+/md/Si_8-tempprofile0/Si-Si.skf
  test/prog/dftb+/md/Si_8-tempprofile0/_autotest.tag
  test/prog/dftb+/md/Si_8-tempprofile0/dftb_in.hsd
  test/prog/dftb+/tests
Labels: bug

#451 Add include path for Ford processing
  doc/dftb+/ford/dftbplus-project-file.md
Labels: Documentation

#401 Charge Model 5
  doc/dftb+/manual/dftbp.tex
  doc/dftb+/manual/manual.bib
  prog/dftb+/lib_common/CMakeLists.txt
  prog/dftb+/lib_common/atomicrad.F90
  prog/dftb+/lib_common/unitconversion.F90
  prog/dftb+/lib_dftbplus/initprogram.F90
  prog/dftb+/lib_dftbplus/inputdata.F90
  prog/dftb+/lib_dftbplus/main.F90
  prog/dftb+/lib_dftbplus/mainio.F90
  prog/dftb+/lib_dftbplus/parser.F90
  prog/dftb+/lib_io/taggedoutput.F90
  prog/dftb+/lib_solvation/CMakeLists.txt
  prog/dftb+/lib_solvation/born.F90
  prog/dftb+/lib_solvation/cm5.F90
  test/prog/dftb+/solvation/gb_cm5/C-C.skf
  test/prog/dftb+/solvation/gb_cm5/C-H.skf
  test/prog/dftb+/solvation/gb_cm5/C-O.skf
  test/prog/dftb+/solvation/gb_cm5/H-C.skf
  test/prog/dftb+/solvation/gb_cm5/H-H.skf
  test/prog/dftb+/solvation/gb_cm5/H-O.skf
  test/prog/dftb+/solvation/gb_cm5/O-C.skf
  test/prog/dftb+/solvation/gb_cm5/O-H.skf
  test/prog/dftb+/solvation/gb_cm5/O-O.skf
  test/prog/dftb+/solvation/gb_cm5/_autotest.tag
  test/prog/dftb+/solvation/gb_cm5/dftb_in.hsd
  test/prog/dftb+/solvation/gb_cm5/struc.xyz
  test/prog/dftb+/tests
Labels: enhancement
