Repository dftbplus/dftbplus, pull requests merged in 2020-09, with the labels that each got.

#618 Allow disabling installation of Python components
  config.cmake
  tools/CMakeLists.txt
Labels: build system

#600 Try to infer libdftbplus location automatically in ctypes API
  tools/pythonapi/src/dftbplus.py
Labels: Python API

#620 Set correct installation locations
  CMakeLists.txt
  cmake/dftbpUtils.cmake
  config.cmake
  external/mudpack/CMakeLists.txt
  prog/dftb+/CMakeLists.txt
  prog/misc/skderivs/CMakeLists.txt
  prog/misc/slakovalue/CMakeLists.txt
  prog/modes/CMakeLists.txt
  prog/transporttools/CMakeLists.txt
  prog/waveplot/CMakeLists.txt
  tools/dptools/CMakeLists.txt
  tools/misc/CMakeLists.txt
  tools/pythonapi/CMakeLists.txt
  utils/test/travis-ci.sh
Labels: build system

#616 Bug fix for unallocated write attempt
  prog/dftb+/lib_dftbplus/main.F90
Labels: bug

#635 Tighten sorting for degeneracies in TD routine
  prog/dftb+/lib_timedep/linrespgrad.F90
  prog/dftb+/lib_timedep/rs_linresp.F90
Labels: bug
