Repository dftbplus/dftbplus, pull requests merged in 2020-03, with the labels that each got.

#399 Fix for optional reference file use
  utils/numcheck/calcderivs
Labels: bug

#410 Fix usage of uninitialized shift vectors with transport
  prog/dftb+/lib_dftb/scc.F90
  prog/dftb+/lib_dftbplus/main.F90
Labels: bug

#407 Updated INSTALL.rst to reflect preprocessor requirement
  INSTALL.rst
Labels: Documentation

#409 Test for inverting no lattice vectors
  prog/dftb+/lib_poisson/structure.F90
Labels: bug

#416 Fix Poisson issue preventing build with several toolchains
  prog/dftb+/lib_poisson/gallocation.F90
Labels: bug

#422 Fix for missing ascii contact shift read
  test/prog/dftb+/transport/H-sheet_grp2/dftb_in.hsd
  test/prog/dftb+/transport/H-sheet_grp4/dftb_in.hsd
  test/prog/dftb+/transport/H-sheet_grp8/dftb_in.hsd
Labels: bug

#424 Added documentation for the contact options
  doc/dftb+/manual/restart_files.tex
  doc/dftb+/manual/transport.tex
Labels: Documentation

#427 Updated to new paper citation
  README.rst
  doc/dftb+/manual/dftbp.tex
  doc/dftb+/manual/introduction.tex
  doc/dftb+/manual/manual.bib
  doc/dftb+/manual/publications.tex
  prog/dftb+/lib_io/formatout.F90
Labels: Documentation, enhancement
