Repository dftbplus/dftbplus, pull requests merged in 2021-11, with the labels that each got.

#890 Fix D3(BJ)-ATM calculations in DFTB+
  CHANGELOG.rst
  src/dftbp/dftb/dispdftd3.F90
  test/app/dftb+/dispersion/2H2O_dftd3_bj/_autotest.tag
  test/app/dftb+/dispersion/DNA_dftd3_bj/_autotest.tag
  test/app/dftb+/dispersion/specieslist_dftd3_bj/_autotest.tag
Labels: bug

#896 Rationalise the ConvergentOnly options
  doc/dftb+/manual/dftbp.tex
  src/dftbp/dftbplus/oldcompat.F90
  src/dftbp/dftbplus/parser.F90
  test/app/dftb+/scc/CH4_nonconverged/_autotest.tag
  test/app/dftb+/scc/CH4_nonconverged/dftb_in.hsd
  test/app/dftb+/tests
Labels: enhancement

#897 Make lapack public instead of interface
  src/dftbp/CMakeLists.txt
Labels: build system
