Repository dftbplus/dftbplus, pull requests merged in 2022-04, with the labels that each got.

#996 Workaround for libNEGF segfault
  src/dftbp/dftbplus/parser.F90
Labels: bug, library: negf

#998 Catch unsupported elements in xTB setup
  src/dftbp/extlibs/tblite.F90
Labels: bug

#953 Rescaling dipole and external fields in solvent
  CHANGELOG.rst
  doc/dftb+/manual/dftbp.tex
  doc/dftb+/manual/packages.tex
  src/dftbp/dftbplus/initprogram.F90
  src/dftbp/dftbplus/inputdata.F90
  src/dftbp/dftbplus/main.F90
  src/dftbp/dftbplus/mainapi.F90
  src/dftbp/dftbplus/mainio.F90
  src/dftbp/dftbplus/oldcompat.F90
  src/dftbp/dftbplus/parser.F90
  src/dftbp/io/taggedoutput.F90
  src/dftbp/solvation/CMakeLists.txt
  src/dftbp/solvation/born.F90
  src/dftbp/solvation/cosmo.F90
  src/dftbp/solvation/fieldscaling.F90
  src/dftbp/solvation/sasa.F90
  src/dftbp/solvation/solvation.F90
  src/dftbp/solvation/solvparser.F90
  src/dftbp/timedep/timeprop.F90
  test/app/dftb+/solvation/H2O_gb_rescale/_autotest.tag
  test/app/dftb+/solvation/H2O_gb_rescale/dftb_in.hsd
  test/app/dftb+/tests
Labels: bug, enhancement

#1002 Read GF electronic temperature correctly
  CHANGELOG.rst
  src/dftbp/dftbplus/parser.F90
  test/app/dftb+/transport/C-chain+Uspin/_autotest.tag
  test/app/dftb+/transport/H-chain-spin/_autotest.tag
Labels: bug

#1003 Arbitrary shell ordering in Poisson solver
  src/dftbp/extlibs/poisson.F90
  src/dftbp/poisson/bulkpot.F90
  src/dftbp/poisson/poisson.F90
  src/dftbp/poisson/structure.F90
  test/app/dftb+/poisson/CH4-selShell/C-C.skf
  test/app/dftb+/poisson/CH4-selShell/C-H.skf
  test/app/dftb+/poisson/CH4-selShell/H-C.skf
  test/app/dftb+/poisson/CH4-selShell/H-H.skf
  test/app/dftb+/poisson/CH4-selShell/_autotest.tag
  test/app/dftb+/poisson/CH4-selShell/dftb_in.hsd
  test/app/dftb+/tests
Labels: enhancement

#832 Time propagation with range separation
  CHANGELOG.rst
  src/dftbp/dftb/populations.F90
  src/dftbp/dftbplus/initprogram.F90
  src/dftbp/timedep/timeprop.F90
  test/app/dftb+/rangesep/C18H12-matrix/dftb_in.hsd
  test/app/dftb+/tests
  test/app/dftb+/timeprop/C4H6_rs/_autotest.tag
  test/app/dftb+/timeprop/C4H6_rs/butadiene.gen
  test/app/dftb+/timeprop/C4H6_rs/dftb_in.hsd
  test/app/dftb+/timeprop/C4H6_rs_Singlet/_autotest.tag
  test/app/dftb+/timeprop/C4H6_rs_Singlet/butadiene.gen
  test/app/dftb+/timeprop/C4H6_rs_Singlet/dftb_in.hsd
  test/app/dftb+/timeprop/C4H6_rs_Triplet/_autotest.tag
  test/app/dftb+/timeprop/C4H6_rs_Triplet/butadiene.gen
  test/app/dftb+/timeprop/C4H6_rs_Triplet/dftb_in.hsd
  test/app/dftb+/timeprop/CH3_dftbu_singlet/_autotest.tag
  test/app/dftb+/timeprop/CH3_dftbu_singlet/dftb_in.hsd
  test/app/dftb+/timeprop/NO_onsite/_autotest.tag
  test/app/dftb+/timeprop/NO_onsite/dftb_in.hsd
  test/app/dftb+/timeprop/NO_pSIC/_autotest.tag
  test/app/dftb+/timeprop/NO_pSIC/dftb_in.hsd
  test/app/dftb+/timeprop/benzene_rs/_autotest.tag
  test/app/dftb+/timeprop/benzene_rs/dftb_in.hsd
Labels: enhancement

#1009 Update README.rst
  test/app/dftb+/README.rst
Labels: Documentation
