Repository dftbplus/dftbplus, pull requests merged in 2022-05, with the labels that each got.

#1024 Append geometry option and device range trap
  doc/dftb+/manual/dftbp.tex
  src/dftbp/dftbplus/input/geoopt.F90
  src/dftbp/dftbplus/main.F90
  src/dftbp/dftbplus/parser.F90
  test/app/dftb+/geoopt/H2O_rf/dftb_in.hsd
Labels: enhancement

#1028 Add more compiler version info to INSTALL.rst
  INSTALL.rst
Labels: Documentation

#1030 Minor memory saving in real H propagation
  src/dftbp/timedep/timeprop.F90
Labels: enhancement

#1039 Trap segfault for optimiser and helical bcs
  src/dftbp/dftbplus/initprogram.F90
  src/dftbp/dftbplus/parser.F90
Labels: bug

#1042 Correction for shell charges with transport
  src/dftbp/dftbplus/main.F90
  test/app/dftb+/transport/H-chain-spin/_autotest.tag
Labels: bug

#1043 Update with output block charges in transport
  src/dftbp/dftbplus/main.F90
  test/app/dftb+/transport/C-chain+U/_autotest.tag
  test/app/dftb+/transport/C-chain+U/device.hsd
  test/app/dftb+/transport/C-chain+U/drain.hsd
  test/app/dftb+/transport/C-chain+U/source.hsd
  test/app/dftb+/transport/C-chain+Uspin/_autotest.tag
  test/app/dftb+/transport/C-chain+Uspin/dftb_in.hsd
Labels: bug

#1044 Fix ready for XLBOMD external potential updates
  src/dftbp/dftbplus/main.F90
Labels: bug, enhancement
