Repository dftbplus/dftbplus, pull requests merged in 2023-11, with the labels that each got.

#1342 Fix definition in header file for testers
  test/src/dftbp/api/mm/testers/testhelpers.h
Labels: debugging

#1341 Change to broadcast of variable in main
  src/dftbp/dftbplus/main.F90
Labels: MPI

#1345 Only set OMP env for MPI test on enabled build
  config.cmake
Labels: CI, MPI

#1346 Fix style guide violation for documenting workarounds
  src/dftbp/dftb/periodic.F90
Labels: Documentation
