Repository dftbplus/dftbplus, pull requests merged in 2023-05, with the labels that each got.

#1226 Reset functionality for new optimizers
  src/dftbp/geoopt/fire.F90
  src/dftbp/geoopt/geoopt.F90
  src/dftbp/geoopt/lbfgs2.F90
  src/dftbp/geoopt/optimizer.F90
  src/dftbp/geoopt/rationalfunc.F90
Labels: enhancement

#1231 Fix integer factorial bug
  src/dftbp/math/factorial.F90
Labels: bug

#1235 NACV compatibility tests happening earlier
  src/dftbp/dftbplus/initprogram.F90
  src/dftbp/timedep/linresp.F90
  src/dftbp/timedep/linrespgrad.F90
  src/dftbp/timedep/linresptypes.F90
Labels: UX

#1238 Hellmann-Feynman test for xTB dipole
  CHANGELOG.rst
  src/dftbp/dftb/hamiltonian.F90
  src/dftbp/dftb/shift.F90
  src/dftbp/dftbplus/main.F90
Labels: enhancement, Hamiltonian: xTB
