Repository dftbplus/dftbplus, pull requests merged in 2023-07, with the labels that each got.

#1200 Electronic Constraints
  CHANGELOG.rst
  doc/dftb+/manual/dftbp.tex
  doc/dftb+/manual/manual.bib
  src/dftbp/dftb/elecconstraints.F90
  src/dftbp/dftb/hamiltonian.F90
  src/dftbp/dftb/shift.F90
  src/dftbp/dftbplus/initprogram.F90
  src/dftbp/dftbplus/input/geoopt.F90
  src/dftbp/dftbplus/inputdata.F90
  src/dftbp/dftbplus/main.F90
  src/dftbp/dftbplus/mainio.F90
  src/dftbp/dftbplus/parser.F90
  src/dftbp/type/wrappedintr.F90
  test/app/dftb+/elecconstraints/H2O_non-converged/_autotest.tag
  test/app/dftb+/elecconstraints/H2O_non-converged/dftb_in.hsd
  test/app/dftb+/elecconstraints/H2O_scc/_autotest.tag
  test/app/dftb+/elecconstraints/H2O_scc/dftb_in.hsd
  test/app/dftb+/elecconstraints/Si8_spin/Si8.gen
  test/app/dftb+/elecconstraints/Si8_spin/_autotest.tag
  test/app/dftb+/elecconstraints/Si8_spin/dftb_in.hsd
  test/app/dftb+/tests
Labels: enhancement

#1255 Fixes and generalises header print
  app/dftb+/dftbplus.F90
  app/transporttools/setupgeom.F90
  src/dftbp/common/CMakeLists.txt
  src/dftbp/common/release.F90
  src/dftbp/dftbplus/parser.F90
  src/dftbp/io/formatout.F90
Labels: enhancement, UX

#1281 Fix for incorrect pointers
  src/dftbp/dftb/periodic.F90
Labels: bug

#1283 Puts the self-neighbour inside the window lock
  src/dftbp/dftb/periodic.F90
Labels: question

#1282 Use common header code
  app/modes/initmodes.F90
  app/waveplot/initwaveplot.F90
Labels: UX

#1288 Correct keyword in setupgeom section
  doc/dftb+/manual/setupgeom.tex
Labels: bug, Documentation

#1284 Fixed window locks called unitialised
  CHANGELOG.rst
  src/dftbp/dftb/periodic.F90
  test/src/dftbp/unittests/dftb/period.F90
Labels: bug
