Repository dftbplus/dftbplus, pull requests merged in 2024-11, with the labels that each got.

#1565 Electronic constraints enabled for xTB models
  doc/dftb+/manual/dftbp.tex
  src/dftbp/dftbplus/parser.F90
  test/app/dftb+/elecconstraints/H2O_gfn1/_autotest.tag
  test/app/dftb+/elecconstraints/H2O_gfn1/dftb_in.hsd
  test/app/dftb+/tests
Labels: enhancement, Hamiltonian: xTB

#1564 Remove blocking of constraints with transport
  doc/dftb+/manual/dftbp.tex
  src/dftbp/dftbplus/initprogram.F90
  test/app/dftb+/elecconstraints/H-chain_transport/30h.gen
  test/app/dftb+/elecconstraints/H-chain_transport/_autotest.tag
  test/app/dftb+/elecconstraints/H-chain_transport/dftb_in.hsd
  test/app/dftb+/elecconstraints/H-chain_transport/shiftcont_drain.dat
  test/app/dftb+/elecconstraints/H-chain_transport/shiftcont_source.dat
  test/app/dftb+/tests
Labels: enhancement, transport

#1462 Symmetric neighbours with solvents
  CHANGELOG.rst
  doc/dftb+/manual/dftbp.tex
  src/dftbp/dftb/hamiltonian.F90
  src/dftbp/dftb/periodic.F90
  src/dftbp/dftbplus/initprogram.F90
  src/dftbp/dftbplus/main.F90
  src/dftbp/dftbplus/parser.F90
  src/dftbp/dftbplus/specieslist.F90
  src/dftbp/io/hsdutils.F90
  src/dftbp/solvation/born.F90
  src/dftbp/solvation/cosmo.F90
  src/dftbp/solvation/sasa.F90
  src/dftbp/solvation/solvation.F90
  src/dftbp/solvation/solvinput.F90
  src/dftbp/solvation/solvparser.F90
  src/dftbp/timedep/timeprop.F90
  test/app/dftb+/solvation/alpb_cation/dftb_in.hsd
  test/app/dftb+/solvation/alpb_p16/dftb_in.hsd
  test/app/dftb+/solvation/cosmo_444/_autotest.tag
  test/app/dftb+/solvation/cosmo_444/dftb_in.hsd
  test/app/dftb+/solvation/cosmo_b33/dftb_in.hsd
  test/app/dftb+/solvation/cosmo_g1/dftb_in.hsd
  test/app/dftb+/solvation/cosmo_i8e/_autotest.tag
  test/app/dftb+/solvation/cosmo_i8e/dftb_in.hsd
  test/app/dftb+/solvation/cosmo_inf/dftb_in.hsd
  test/app/dftb+/solvation/cosmo_inf_gfn1/_autotest.tag
  test/app/dftb+/solvation/cosmo_inf_gfn1/dftb_in.hsd
  test/app/dftb+/solvation/cosmo_inf_gfn1/struc.xyz
  test/app/dftb+/solvation/cosmo_nitralin/dftb_in.hsd
  test/app/dftb+/solvation/cosmo_quinoline/dftb_in.hsd
  test/app/dftb+/solvation/gb_specieslist/_autotest.tag
  test/app/dftb+/solvation/gb_specieslist/dftb_in.hsd
  test/app/dftb+/tests
Labels: bug

#1569 Fix return of uninitialized modifier with isDefaultExported
  src/dftbp/io/hsdutils.F90
Labels: bug

#1573 Fix string trunction in variable tag
  src/dftbp/io/taggedoutput.F90
Labels: bug, regression tests
