Repository dftbplus/dftbplus, pull requests merged in 2024-12, with the labels that each got.

#1571 Enforce SCC for hybrid hamiltonians
  doc/dftb+/manual/dftbp.tex
  src/dftbp/dftbplus/initprogram.F90
  src/dftbp/dftbplus/oldcompat.F90
  src/dftbp/dftbplus/parser.F90
  test/app/dftb+/hybrid/cluster/Benzene-Spinpol-matrix/dftb_in.hsd
  test/app/dftb+/hybrid/cluster/Benzene-TD-LC-Spinpol-Force/dftb_in.hsd
  test/app/dftb+/hybrid/cluster/Thymine-spin-matrix-force-mpi-grp1/dftb_in.hsd
  test/app/dftb+/hybrid/cluster/Thymine-spin-matrix-force-restart/dftb_in1.hsd
  test/app/dftb+/hybrid/cluster/Thymine-spin-matrix-force-restart/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-gamma-matrix-force-cam/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-gamma-matrix-restart-ascii/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-gamma-matrix-restart-ascii/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-gamma-matrix-restart/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-gamma-matrix-restart/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-gamma-neigh-force-cam/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-gamma-neigh-force-hyb/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-gamma-neigh-force-lc/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-band/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-band/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-force-lc/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-lc/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-I/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-I/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-II/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-II/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-ascii/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-ascii/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-band/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-band/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-force-lc/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-restart-ascii/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-restart-ascii/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-restart/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-restart/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-matrix-ct-kpts/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-neigh-ct-kpts/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Benzene-gamma-matrix-spin-force-grp1/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Benzene-gamma-neigh-spin-force/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/CN-chain_transl-inv-matrix-ct/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/CN-chain_transl-inv-neigh-ct/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-gamma-matrix/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-gamma-neigh/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-gamma-restart/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/GaAs-gamma-restart/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-matrix-ct-anderson/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-matrix-ct-diis/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-matrix-ct-simple/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-matrix-ct/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-neigh-ct/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-neigh-mic/dftb_in.hsd
Labels: UX

#1533 Informative error for spin constants
  src/dftbp/dftbplus/parser.F90
Labels: UX

#1575 Check old parser sets scc for hybrids
  src/dftbp/dftbplus/oldcompat.F90
  src/dftbp/dftbplus/parser.F90
  test/app/dftb+/hybrid/cluster/Thymine-spin-matrix-force-mpi-grp2/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-band-np2/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-band-np2/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-band-np3/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-band-np3/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-band-np4/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-band-np4/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-force-lc-np2/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-force-lc-np3/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-force-lc-np4/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-np2/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-np2/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-np3/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-np3/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-np4/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-matrix-restart-np4/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-band-mpi/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-band-mpi/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-restart-mpi/dftb_in1.hsd
  test/app/dftb+/hybrid/periodic/Acene-kpts-neigh-restart-mpi/dftb_in2.hsd
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-matrix-ct-kpts-np2/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-matrix-ct-kpts-np3/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-matrix-ct-kpts-np4/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-neigh-ct-kpts-mpi/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Benzene-gamma-matrix-spin-force-grp2/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-matrix-ct-np2/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-matrix-ct-np3/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-matrix-ct-np4/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-neigh-ct-mpi/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/GaAs-kpts-neigh-mic-mpi/dftb_in.hsd
Labels: enhancement, UX

#1576 Update GitHub workflows
  .github/workflows/build.yml
Labels: CI

#1588 Restore unit tests for math directory
  test/src/dftbp/unittests/CMakeLists.txt
  test/src/dftbp/unittests/math/CMakeLists.txt
  test/src/dftbp/unittests/math/matrixoperations.F90
  test/src/dftbp/unittests/math/matrixops.F90
Labels: unit tests

#1593 Waveplot superposition of atomic densities
  CHANGELOG.rst
  app/waveplot/waveplot.F90
Labels: bug
