Repository dftbplus/dftbplus, pull requests merged in 2024-01, with the labels that each got.

#1367 Possible bug when deltaRhoOut generated
  src/dftbp/dftbplus/main.F90
Labels: bug, question

#1372 Enable spin-polarized general k-point hybrid path
  src/dftbp/dftb/hybridxc.F90
  src/dftbp/dftbplus/initprogram.F90
  src/dftbp/dftbplus/main.F90
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-neigh-ct-kpts-mpi/_autotest.tag
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-neigh-ct-kpts-mpi/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-neigh-ct-kpts-mpi/geo.gen
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-neigh-ct-kpts/_autotest.tag
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-neigh-ct-kpts/dftb_in.hsd
  test/app/dftb+/hybrid/periodic/Benzene-box-spin-neigh-ct-kpts/geo.gen
  test/app/dftb+/tests
Labels: enhancement

#1343 Print error status on test fail
  test/app/dftb+/bin/autotest2
Labels: CI, debugging

#1374 Fixes problem in parser for bulk BC read
  src/dftbp/dftbplus/parser.F90
Labels: bug

#1377 Remove -ip option for ifx/icx compiler
  sys/intel.cmake
Labels: build system

#1376 Clarify error message a bit for users
  src/dftbp/timedep/timeprop.F90
Labels: UX
