Repository dftbplus/dftbplus, pull requests merged in 2025-01, with the labels that each got.

#1604 Move nLocal* sizing out of hybrids
  src/dftbp/dftbplus/initprogram.F90
Labels: MPI

#1606 Fix for case where a slice is passed
  src/dftbp/dftb/hybridxc.F90
Labels: bug

#1602 Missed language compatability in parser
  src/dftbp/dftbplus/parser.F90
Labels: UX

#1609 Start of internal code document
  doc/dftb+/code/Makefile
  doc/dftb+/code/make.bat
  doc/dftb+/code/source/conf.py
  doc/dftb+/code/source/index.rst
  doc/dftb+/code/source/testing.rst
  doc/dftb+/code/source/testing/introduction.rst
  doc/dftb+/code/source/testing/regression.rst
Labels: Documentation, unit tests

#1614 Skip invalid test configuration
  test/src/dftbp/api/mm/tests
Labels: regression tests
